### ISSUE TITLE
What to enter as Device Name

### ISSUE THREAD

**Issue by RequestFX** [DavidBuchanan314/pwn-mbr#2]
Sorry for this noob question but I dont know what to put at "Usage: '%s DEVICE'\n".

I tried \\.\PhysicalDrive0 aswell as other things but could not figure it out.

**Comment by DavidBuchanan314** [comment]
This is intended to run on Linux, I'm not sure if it would work under windows, and idk the windows device naming scheme.

**Comment by RequestFX** [comment]
> 
> 
> This is intended to run on Linux, I'm not sure if it would work under windows, and idk the windows device naming scheme.

I have a linux machine setup but I still dont know what to enter. Will this mbr overwrite work on windows though?

**Comment by DavidBuchanan314** [comment]
I can't answer that question without knowledge of your system setup. `/dev/sda` is common, for systems with sata-based drives.
