### ISSUE TITLE
Segfault after "Copying original MBR."

### ISSUE THREAD

**Issue by nullNullNone** [DavidBuchanan314/pwn-mbr#3]
root@ubuntu:/home/asdf/pwn-mbr-master# ./inject /dev/sda
Injecting to /dev/sda
Empty sector found at offset 0x0000ca00. Copying original MBR.
Segmentation fault (core dumped)

**Comment by DavidBuchanan314** [comment]
This is probably the bug:

https://github.com/DavidBuchanan314/pwn-mbr/blob/master/inject.c#L69-L70

I'm checking the wrong variable - it should be `payloadfp == NULL`.

If the file failed to open, there'll be a null dereference on line 76.

Does the `payload` file exist? (was is successfully assembled?)

**Comment by DavidBuchanan314** [comment]
Probably fixed in df2395988e20a45d6a5bdda650b684109b234dab
